# Exact export verification for supported platforms.
# Invoked with -DLIBS=<path>|<path> -DSYS=<CMAKE_SYSTEM_NAME> [-DLINKER=<link.exe>].
# Fails (does not skip) when the required platform tool is unavailable.
string(REPLACE "|" ";" LIBS "${LIBS}")

function(require_exact_symbols output)
	foreach(symbol CreateBonDriver CreateBonStruct)
		set(found FALSE)
		string(REPLACE "\n" ";" lines "${output}")
		foreach(line ${lines})
			if(line MATCHES "[ \t](T|W)[ \t]+_?${symbol}$")
				set(found TRUE)
			endif()
		endforeach()
		if(NOT found)
			message(FATAL_ERROR "library does not export exact symbol ${symbol}")
		endif()
	endforeach()
endfunction()

if(SYS STREQUAL "Windows")
	if(DUMPBIN)
		set(DUMPBIN_EXE "${DUMPBIN}")
	else()
		unset(DUMPBIN_EXE CACHE)
		unset(DUMPBIN_EXE)
	endif()
	if(NOT DUMPBIN_EXE AND LINKER)
		get_filename_component(linker_dir "${LINKER}" DIRECTORY)
		find_program(DUMPBIN_EXE NAMES dumpbin dumpbin.exe PATHS "${linker_dir}" NO_DEFAULT_PATH)
	endif()
	if(NOT DUMPBIN_EXE)
		find_program(DUMPBIN_EXE NAMES dumpbin dumpbin.exe)
	endif()
	if(NOT DUMPBIN_EXE)
		message(FATAL_ERROR "dumpbin is required for Windows export verification but was not found")
	endif()
	foreach(lib IN ITEMS ${LIBS})
		if(NOT EXISTS "${lib}")
			message(FATAL_ERROR "library does not exist: ${lib}")
		endif()
		execute_process(COMMAND "${DUMPBIN_EXE}" /nologo /exports "${lib}" OUTPUT_VARIABLE out RESULT_VARIABLE rc)
		if(NOT rc EQUAL 0)
			message(FATAL_ERROR "dumpbin failed on ${lib}")
		endif()
		foreach(symbol CreateBonDriver CreateBonStruct)
			set(found FALSE)
			string(REPLACE "\n" ";" export_lines "${out}")
			foreach(export_line ${export_lines})
				string(STRIP "${export_line}" export_line)
				if(export_line MATCHES "^[0-9]+[ \t]+[0-9]+[ \t]+[0-9A-Fa-f]+[ \t]+${symbol}([ \t]+=[ \t].*)?$")
					set(found TRUE)
				endif()
			endforeach()
			if(NOT found)
				message(FATAL_ERROR "${lib} does not export exact undecorated ${symbol}")
			endif()
		endforeach()
		get_filename_component(name "${lib}" NAME)
		if(name MATCHES "^lib")
			message(FATAL_ERROR "unexpected 'lib' prefix on ${name}")
		endif()
		message(STATUS "export check ok: ${name}")
	endforeach()
	return()
endif()

find_program(NM_EXECUTABLE nm)
if(NOT NM_EXECUTABLE)
	message(FATAL_ERROR "nm is required for ${SYS} export verification but was not found")
endif()

if(SYS STREQUAL "Linux")
	set(NM_ARGS -D --defined-only)
elseif(SYS STREQUAL "Darwin")
	set(NM_ARGS -gU)
else()
	message(FATAL_ERROR "no export verification defined for ${SYS}")
endif()

foreach(lib IN ITEMS ${LIBS})
	if(NOT EXISTS "${lib}")
		message(FATAL_ERROR "library does not exist: ${lib}")
	endif()
	execute_process(COMMAND ${NM_EXECUTABLE} ${NM_ARGS} "${lib}" OUTPUT_VARIABLE symbols RESULT_VARIABLE rc)
	if(NOT rc EQUAL 0)
		message(FATAL_ERROR "nm failed on ${lib}")
	endif()
	require_exact_symbols("${symbols}")
	get_filename_component(name "${lib}" NAME)
	if(name MATCHES "^lib")
		message(FATAL_ERROR "unexpected 'lib' prefix on ${name}")
	endif()
	message(STATUS "export check ok: ${name}")
endforeach()
